version: '3'

services:
  db:
    image: postgres:12.4\l
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example